name: finora
description: Finora - Personal Finance Management
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  google_generative_ai: ^0.4.4
  flutter_dotenv: ^5.0.2


  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0
  firebase_database: ^11.0.4

  # Charts
  fl_chart: ^0.60.0

  # Speech-to-text
  speech_to_text: 7.3.0

  # Notifications
  flutter_local_notifications: ^17.1.2

  # HTTP (for AI requests)
  http: ^1.1.0

  # Utilities
  intl: ^0.18.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
